steal("jquery/class",function(b){b.Class("MP.Editor",{myThis:null,eventPrefix:"MPCE-",on:function(a,c){a=a.split(" ").map(function(a){return MP.Editor.eventPrefix+a}).join(" ");b(window).on(a,c)},onIfr:function(a,c){a=a.split(" ").map(function(a){return MP.Editor.eventPrefix+a}).join(" ");CE.Iframe.window.jQuery(CE.Iframe.window).on(a,c)},oneIfr:function(a,c){a=a.split(" ").map(function(a){return MP.Editor.eventPrefix+a}).join(" ");CE.Iframe.window.jQuery(CE.Iframe.window).one(a,c)},trigger:function(a,
c){a=a.split(" ").map(function(a){return MP.Editor.eventPrefix+a}).join(" ");b(window).trigger(a,c)},triggerIfr:function(a,c){a=a.split(" ").map(function(a){return MP.Editor.eventPrefix+a}).join(" ");CE.Iframe.window.jQuery(CE.Iframe.window).trigger(a,c)},triggerEverywhere:function(a,c){MP.Editor.trigger(a,c);MP.Editor.triggerIfr(a,c)}},{loaded:!1,opened:!1,preloader:null,flash:null,utils:null,settings:null,lang:null,init:function(){MP.Editor.myThis=this;new MP.Preloader(b("#motopress-preload"));
new MP.Flash(b("#motopress-flash"));new MP.Utils;new MP.Settings;new MP.Language;new CE.Navbar(b(".motopress-content-editor-navbar"));new CE.PreviewDevice(b("#motopress-content-editor-preview-device-panel"));new CE.Iframe(b("#motopress-content-editor-scene"));new CE.CodeModal(b("#motopress-code-editor-modal"));MP.Preloader.myThis.load(MP.Editor.shortName);this.open()},load:function(){this.loaded=!0;MP.Editor.triggerEverywhere("EditorLoad")},unload:function(){this.loaded=!1;MP.Editor.trigger("EditorUnLoad")},
open:function(){this.opened=!0;MP.Editor.trigger("EditorOpen")},close:function(){this.opened=!1;this.unload();MP.Editor.trigger("EditorClose")},isOpen:function(){return this.opened}})});
steal("jquery/controller",function(b){b.Controller("MP.Preloader",{myThis:null},{stages:{Navbar:!1,Language:!1,Iframe:!1,LeftBar:!1,DragDrop:!1,Editor:!1},loaded:0,step:null,knob:null,init:function(){MP.Preloader.myThis=this;this.step=Math.round(100/Object.keys(this.stages).length*100)/100;this.knob=this.element.find("#motopress-knob");this.set()},reopen:function(){for(var a in this.stages)"Navbar"===a||"Language"===a?delete this.stages[a]:this.stages[a]=!1},show:function(){this.loaded=0;this.set();
this.element.show()},hide:function(){this.element.fadeOut("slow");MP.Flash.showMessage()},load:function(a){this.stages.hasOwnProperty(a)&&!this.stages[a]&&(this.stages[a]=!0,this.loaded+=this.step,this.set())},set:function(){this.knob.val(this.loaded).trigger("change")}})});
steal("jquery/controller",function(b){b.Controller("MP.Flash",{myThis:null,setFlash:function(a,c){var d=MP.Flash.myThis.create();"undefined"===typeof c&&(c="warning");var b="";switch(c){case "info":b="alert-info";break;case "success":b="alert-success";break;case "error":b="alert-error"}b.length&&d.addClass(b);a.length&&d.children("span").html(a)},showMessage:function(){MP.Flash.myThis.element.children(".alert").each(function(){var a=b(this);a.show().mpalert();var c=setTimeout(function(){a.mpalert("close");
clearTimeout(c)},1E4)})}},{alertEl:b("<div />",{"class":"alert fade in",style:"display: none;"}),closeEl:b("<div />",{"class":"motopress-close motopress-icon-remove","data-dismiss":"alert"}),messageEl:b("<span />"),create:function(){return this.alertEl.clone().append(this.closeEl.clone(),this.messageEl.clone()).appendTo(this.element)},init:function(){MP.Flash.myThis=this}})});
steal("jquery/class",function(b){b.Class("MP.Utils",{validationError:b("<div />",{"class":"motopress-validation-error"}),tbStyle:null,wpFrontEndEditorEvents:[],strtr:function(a,c,d){if("object"===typeof c){d="";for(var b=0;b<a.length;b++)d+="0";var f=0,f=-1,b="";for(fr in c)for(f=0;-1!=(f=a.indexOf(fr,f));)if(0!=parseInt(d.substr(f,fr.length)))f+=1;else{for(var g=0;g<c[fr].length;g++)b+="1";d=d.substr(0,f)+b+d.substr(f+fr.length,d.length-(f+fr.length));a=a.substr(0,f)+c[fr]+a.substr(f+fr.length,a.length-
(f+fr.length));f=f+c[fr].length+1;b=""}return a}for(b=0;b<c.length;b++)a=a.replace(new RegExp(c.charAt(b),"g"),d.charAt(b));return a},uniqid:function(a,c){"undefined"==typeof a&&(a="");var d,b=function(a,c){a=parseInt(a,10).toString(16);return c<a.length?a.slice(a.length-c):c>a.length?Array(1+(c-a.length)).join("0")+a:a};this.php_js||(this.php_js={});this.php_js.uniqidSeed||(this.php_js.uniqidSeed=Math.floor(123456789*Math.random()));this.php_js.uniqidSeed++;d=a+b(parseInt((new Date).getTime()/1E3,
10),8);d+=b(this.php_js.uniqidSeed,5);c&&(d+=(10*Math.random()).toFixed(8).toString());return d},version_compare:function(a,c,d){this.php_js=this.php_js||{};this.php_js.ENV=this.php_js.ENV||{};var b=0,f=0,g=0,h={dev:-6,alpha:-5,a:-5,beta:-4,b:-4,RC:-3,rc:-3,"#":-2,p:1,pl:1},b=function(a){a=(""+a).replace(/[_\-+]/g,".");a=a.replace(/([^.\d]+)/g,".$1.").replace(/\.{2,}/g,".");return a.length?a.split("."):[-8]},k=function(a){return a?isNaN(a)?h[a]||-7:parseInt(a,10):0};a=b(a);c=b(c);f=Math.max(a.length,
c.length);for(b=0;b<f;b++)if(a[b]!=c[b])if(a[b]=k(a[b]),c[b]=k(c[b]),a[b]<c[b]){g=-1;break}else if(a[b]>c[b]){g=1;break}if(!d)return g;switch(d){case ">":case "gt":return 0<g;case ">=":case "ge":return 0<=g;case "<=":case "le":return 0>=g;case "==":case "=":case "eq":return 0===g;case "<>":case "!=":case "ne":return 0!==g;case "":case "<":case "lt":return 0>g;default:return null}},inObject:function(a,c){var b=!1,e;for(e in c)if(c[e].toLowerCase()==a.toLowerCase()){b=!0;break}return b},removeByValue:function(a,
c){return-1!==c.indexOf(a)?(c.splice(c.indexOf(a),1),!0):!1},doSortSelectByText:function(a){if(a.children("optgroup").length)a.children("optgroup").each(function(){var a=b.makeArray(b(this).children("option")).sort(function(a,c){return b(a).text()>b(c).text()?1:b(a).text()<b(c).text()?-1:0});b(this).empty().html(a)});else{var c=b.makeArray(a.children("option")).sort(function(a,c){return b(a).text()>b(c).text()?1:b(a).text()<b(c).text()?-1:0});a.empty().html(c)}},addParamToUrl:function(a,c,b){var e=
a.indexOf("?"),f=a.indexOf("#");e==a.length-1&&(a=a.substring(0,e),e=-1);return(0<f?a.substring(0,f):a)+(0<e?"&"+c+"="+b:"?"+c+"="+b)+(0<f?a.substring(f):"")},removeParamFromUrl:function(a,c){var b=a.match(new RegExp(c+"\\=([a-z0-9]+)","i"));b&&(b=b[0],0<=a.search("&"+b)?a=a.replace("&"+b,""):0<=a.search("\\?"+b+"&")?a=a.replace("?"+b+"&",""):0<=a.search("\\?"+b)&&(a=a.replace("?"+b,"")));return a},showValidationError:function(a,c){var b=c.next(".motopress-validation-error");b.length&&b.remove();
this.validationError.clone().text(a).insertAfter(c)},getScrollbarWidth:function(){var a=window.browserScrollbarWidth;if("undefined"===typeof a){var c=b('<div style="width: 50px; height: 50px; position: absolute; left: -100px; top: -100px; overflow: auto;"><div style="width: 1px; height: 100px;"></div></div>');b("body").append(c);a=c[0].offsetWidth-c[0].clientWidth;c.remove()}return a},getSpanClass:function(a){for(var c=new RegExp("^("+parent.CE.Iframe.myThis.gridObj.span["class"]+")\\d{1,2}$","i"),
b=null,e=0;e<a.length;e++)if(c.test(a[e])){b=a[e];break}return b},getSpanNumber:function(a){return parseInt(a.match(/\d{1,2}/i))},notClone:function(a,c){return null===c||a[0]!==c.draggable[0]&&a[0]!==c.helper[0]?!0:!1},calcSpanNumber:function(a,c){var d=(a.hasClass("motopress-row-edge")?a:a.find(".motopress-row-edge").first()).children(".motopress-clmn"),e=0;d.length&&d.each(function(){if(MP.Utils.notClone(b(this),c)){var a=MP.Utils.getSpanNumber(MP.Utils.getSpanClass(b(this).prop("class").split(" ")));
e+=a}});return e},getEdgeSpan:function(a){return a.hasClass("motopress-clmn-edge")?a:a.find(".motopress-clmn-edge").first()},getEdgeRow:function(a){return a.hasClass("motopress-row-edge")?a:a.find(".motopress-row-edge").first()},detectSpanNestingLvl:function(a){return a.closest(".motopress-row").parent(".motopress-content-wrapper").length?1:2},detectRowNestingLvl:function(a){return a.parent(".motopress-content-wrapper").length?1:2},getHandleClass:function(a){for(var c=/^ui-resizable-(n|e|s|w|se|sw)$/i,
b=null,e=0;e<a.length;e++)if(c.test(a[e])){b=a[e];break}return b},setup:function(){var a=navigator.userAgent.toLowerCase();this.Browser={Version:(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],Chrome:/chrome/.test(a),Safari:/webkit/.test(a),Opera:/opera/.test(a),IE:/msie/.test(a)&&!/opera/.test(a),Mozilla:/mozilla/.test(a)&&!/(compatible|webkit)/.test(a)}},getEditorActiveMode:function(a){for(var c=/^(tmce|html)-active$/i,b=null,e=0;e<a.length;e++)c.test(a[e])&&(b=a[e]);return b},addWindowFix:function(){"function"===
typeof tb_show&&"function"===typeof tb_remove&&(this.tbStyle=b("<style />",{type:"text/css",text:"#TB_overlay {z-index: 1051;} #TB_window {z-index: 1052;}"}).appendTo("head"))},removeWindowFix:function(){null!==this.tbStyle&&this.tbStyle.remove()},base64_decode:function(a){var c,b,e,f,g,h=0,k=0;f="";var m=[];if(!a)return a;a+="";do c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(h++)),b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(h++)),
f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(h++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(h++)),e=c<<18|b<<12|f<<6|g,c=e>>16&255,b=e>>8&255,e&=255,64==f?m[k++]=String.fromCharCode(c):64==g?m[k++]=String.fromCharCode(c,b):m[k++]=String.fromCharCode(c,b,e);while(h<a.length);f=m.join("");return f=this.utf8_decode(f)},base64_encode:function(a){var c,b,e,f,g=0,h=0,k="",k=[];if(!a)return a;a=this.utf8_encode(a+"");
do c=a.charCodeAt(g++),b=a.charCodeAt(g++),e=a.charCodeAt(g++),f=c<<16|b<<8|e,c=f>>18&63,b=f>>12&63,e=f>>6&63,f&=63,k[h++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f);while(g<a.length);k=k.join("");a=a.length%3;return(a?k.slice(0,a-3):
k)+"===".slice(a||3)},utf8_decode:function(a){var c=[],b=0,e=0,f=0,g=0,h=0;for(a+="";b<a.length;)f=a.charCodeAt(b),128>f?(c[e++]=String.fromCharCode(f),b++):191<f&&224>f?(g=a.charCodeAt(b+1),c[e++]=String.fromCharCode((f&31)<<6|g&63),b+=2):(g=a.charCodeAt(b+1),h=a.charCodeAt(b+2),c[e++]=String.fromCharCode((f&15)<<12|(g&63)<<6|h&63),b+=3);return c.join("")},utf8_encode:function(a){if(null===a||"undefined"===typeof a)return"";a+="";var c="",b,e,f=0;b=e=0;for(var f=a.length,g=0;g<f;g++){var h=a.charCodeAt(g),
k=null;128>h?e++:k=127<h&&2048>h?String.fromCharCode(h>>6|192)+String.fromCharCode(h&63|128):String.fromCharCode(h>>12|224)+String.fromCharCode(h>>6&63|128)+String.fromCharCode(h&63|128);null!==k&&(e>b&&(c+=a.slice(b,e)),c+=k,b=e=g+1)}e>b&&(c+=a.slice(b,f));return c},nl2br:function(a,c){return(a+"").replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,"$1"+(c||"undefined"===typeof c?"<br />":"<br>")+"$2")},br2nl:function(a){return a.replace(/<br[^>]*>\s*\r*\n*/g,"\n")},addWpFrontEndEditorFix:function(){var a=
b("#post-preview").data("events");"undefined"!==typeof a&&a.hasOwnProperty("click")&&(a=a.click.slice(),b.each(a,function(a,d){-1!==d.handler.toString().indexOf("wp_fee_redirect")&&(MP.Utils.wpFrontEndEditorEvents.push(d),b("#post-preview").data("events").click.splice(b("#post-preview").data("events").click.indexOf(d),1))}))},removeWpFrontEndEditorFix:function(){this.wpFrontEndEditorEvents.length&&(b.merge(b("#post-preview").data("events").click,this.wpFrontEndEditorEvents),this.wpFrontEndEditorEvents.length=
0)},getTinyMCEVersion:function(){return"undefined"!==typeof tinyMCE?tinyMCE.majorVersion+"."+tinyMCE.minorVersion:!1},fixTabsBaseTagConflict:function(a,c,d){c=b("undefined"===typeof c?document:c);d="undefined"===typeof d?location:d;c.find("base").length&&a.find("ul li a").each(function(){b(this).attr("href",d.href.toString()+b(this).attr("href"))})},getObjectChanges:function(a,c){var d={},e;for(e in c)if(!a||a[e]!==c[e])if(b.isPlainObject(c[e])){var f=getObjectChanges(a[e],c[e]);b.isEmptyObject(f)||
(d[e]=f)}else d[e]=c[e];return d},moveArrayElement:function(a,c,b){a.splice(b,0,a.splice(c,1)[0])}},{})});
steal("jquery/controller",function(b){b.Controller("CE.Iframe",{myThis:null,window:null,$window:null,contents:null,wpEditor:null,wpTextarea:null},{minWidth:null,gridObj:null,grid:b("<div />",{id:"motopress-ce-grid","class":"mp-container"}),divDisablePlugin:b("<div />",{"class":"motopress-disable-plugin"}),isHeadwayTheme:null,body:null,sceneContent:null,sceneContainer:null,rowExample:null,wpAttachmentDetails:[],$form:b("form#mpce-form"),$postForm:b("form#post"),$postFormMPFields:b("form#post .mpce-form-fields:eq(0)"),
init:function(a){CE.Iframe.myThis=this;CE.Iframe.window=this.element[0].contentWindow;CE.Iframe.$window=b(CE.Iframe.window);CE.Iframe.wpTextarea=b("#wp-content-editor-container #content");a.addClass("motopress-tmp-iframe-width");CE.Iframe.myThis.gridObj=parent.motopressCE.settings.library.grid;CE.Iframe.myThis.getTinyMCEContent();a.one("load",CE.Iframe.myThis.proxy("onLoad"))},destroy:function(){b(CE.Iframe.window).off("beforeunload.CE.Iframe");b(parent.window).off("beforeunload.CE.Iframe");CE.Iframe.window.CE.Dialog.myThis._destroy();
CE.Navbar.myThis._destroy();this._super()},onLoad:function(){CE.Iframe.myThis.wpAttachmentDetails=CE.Iframe.window.mpce_wp_attachment_details;CE.Iframe.contents=this.element.contents();CE.Navbar.myThis.onIframeLoad(this.element);CE.Iframe.contents.find('link[href*="js_composer"]').remove();MP.Utils.addWpFrontEndEditorFix();var a=CE.Iframe.contents.find("head")[0],c=b("<script />",{text:'var steal = { production: "mp/ce/iframeProd/production.js" + parent.motopress.pluginVersionParam };'})[0];this.appendScript(a,
c);c=b("<script />",{src:MP.Settings.pluginDirUrl+"steal/steal.production.js?mp/ce/iframeProd"})[0];this.appendScript(a,c);this.body=CE.Iframe.contents.find("body");this.sceneContent=this.body.find(".motopress-content-wrapper");this.preventUnload();this.body.find("#wp-motopress-tmp-editor-wrap").hide();this.sceneContent.length||(this.body.append(this.divDisablePlugin),this.isHeadwayTheme?MP.Flash.setFlash(localStorage.getItem("CENeedHeadwayThemeGrid"),"error"):MP.Flash.setFlash(localStorage.getItem("CENeedContentOutput"),
"error"));this.element.removeClass("motopress-tmp-iframe-width");a=this.sceneContent.width();this.body.addClass("motopress-body");this.sceneContent.find("script").remove();this.sceneContent.wrap('<div class="'+CE.Iframe.myThis.gridObj.span.fullclass+'" />').parent().wrap('<div class="'+CE.Iframe.myThis.gridObj.row["class"]+" "+CE.Iframe.myThis.gridObj.row.edgeclass+' motopress-row" />').parent().wrap('<div id="motopress-container" class="mp-container" />');this.sceneContainer=this.sceneContent.closest("#motopress-container");
this.rowExample=this.sceneContainer.children(".motopress-row");var c=this.sceneContainer.parents(),d=c.length-3;c.each(function(a){b(this).addClass("motopress-overflow-visible");return a<d});c=parseFloat(this.rowExample.css("margin-left"));this.rowExample.attr("data-margin-left",c);this.sceneContent.find("."+CE.Iframe.myThis.gridObj.span.minclass+".motopress-clmn").addClass("motopress-clmn-min");this.setSceneWidth(a);this.unwrapGrid();this.body.prepend(this.grid);b("body").hide(0,function(){b("body").show()})},
setSceneWidth:function(a){this.sceneContainer.css("max-width","");a="undefined"!==typeof a?a:this.sceneContent.width();var c=CE.Iframe.contents.width(),b=parseFloat(this.rowExample.css("margin-left")),e=parseFloat(this.rowExample.css("margin-right"));a=a-b-e;a>c&&(a=c+(b+e));this.sceneContainer.css("max-width",a);this.grid.css("max-width",a)},unwrapGrid:function(){this.body.find('div[data-motopress-group="mp_grid"]').each(function(){var a=b(this),c=a.attr("data-motopress-group"),d=a.attr("data-motopress-shortcode"),
e=a.attr("data-motopress-parameters"),f=a.attr("data-motopress-styles"),a=a.children("div");a.attr("data-motopress-group",c);a.attr("data-motopress-shortcode",d);e.length&&a.attr("data-motopress-parameters",e);f.length&&a.attr("data-motopress-styles",f);a.unwrap()})},renderContent:function(a,c,d,e){"undefined"===typeof a&&(a="");"undefined"===typeof c&&(c="");"undefined"===typeof d&&(d="");"undefined"===typeof e&&(e="");c=c.replace(/(?:<p>)?\x3c!--more(.*?)?--\x3e(?:<\/p>)?/,'<section class="mpce-wp-more-tag"></section>').replace(/(?:<p>)?\x3c!--more(.*?)?--\x3e(?:<\/p>)?/,
"");var f=b("#motopress-ce-btn").data("post-status");this.$form.find('[name="mpce_title"]').val(a);this.$form.find('[name="mpce_editable_content"]').val(c);this.$form.find('[name="mpce_viewable_content"]').val(d);this.$form.find('[name="mpce_page_template"]').val(e);a=new RegExp("\\[/"+CE.Iframe.myThis.gridObj.row.shortcode+"\\]","ig");c.length&&!a.test(c)&&MP.Flash.setFlash(localStorage.getItem("CEDefaultWPEditor"),"info");CE.Iframe.myThis.isHeadwayTheme=motopressCE.info.is_headway_themes;"string"===
typeof CE.Iframe.myThis.isHeadwayTheme&&(CE.Iframe.myThis.isHeadwayTheme=parseInt(CE.Iframe.myThis.isHeadwayTheme));if("auto-draft"===f){c=this.$postForm.attr("target");var g=this.$form.find(".mpce-form-fields:eq(0)");this.$postForm.attr("target","motopress-content-editor-scene");this.$postFormMPFields.html(g.html());this.$postFormMPFields.find("[name]").each(function(){b(this).val(g.find('[name="'+b(this).attr("name")+'"]').val())});this.$postFormMPFields.append(b("<input>",{type:"hidden",name:"mpce_auto_draft_redirect",
value:this.$form.attr("action")}));this.$postForm.submit();"undefined"===typeof c?this.$postForm.removeAttr("target"):this.$postForm.attr("target",c);this.$postFormMPFields.html("")}else this.$form.submit();MP.Preloader.myThis.load(CE.Iframe.shortName)},getTinyMCEContent:function(){if(wp.hasOwnProperty("autosave"))var a=wp.autosave.getPostData();else(a="undefined"!==typeof tinymce&&tinymce.get("content"))&&!a.isHidden()&&a.save(),a={post_title:b("#title").val()||"",content:b("#content").val()||"",
excerpt:b("#excerpt").val()||""};var c=this,d=a.post_title,e=a.content,a=b('[name="page_template"]'),f=a.length?a.val():"";"undefined"!==typeof tinyMCE?(a=MP.Utils.getEditorActiveMode(b("#wp-content-wrap").prop("class").split(" ")),CE.Iframe.wpEditor=tinyMCE.get("content"),"html-active"===a?(switchEditors.hasOwnProperty("switchto")?switchEditors.switchto(b("#content-tmce")[0]):switchEditors.go("content","tmce"),"undefined"===typeof CE.Iframe.wpEditor||null===CE.Iframe.wpEditor?b.when(motopressCE.tinyMCEEditorInited).done(function(a){CE.Iframe.wpEditor=
a;c.renderContent(d,c.getEditableContent(CE.Iframe.wpEditor),e,f)}):c.renderContent(d,c.getEditableContent(CE.Iframe.wpEditor),e,f)):c.renderContent(d,c.getEditableContent(CE.Iframe.wpEditor),e,f)):c.renderContent(d,c.getEditableContent(null),e,f)},getEditableContent:function(a){return a?a.getContent({format:"html"}):CE.Iframe.wpTextarea.val().length?switchEditors._wp_Autop(CE.Iframe.wpTextarea.val()).replace(RegExp("\n","g"),""):""},appendScript:function(a,c){a.appendChild(c)},prependScript:function(a,
c){a.insertBefore(c,a.firstChild)},wpLinkCloseCallback:function(a){b("#wp-link").on("wpdialogclose.motopress",function(c){b("#wp-link").off("wpdialogclose.motopress");a()})},preventUnload:function(){this.body.find("a").on("click",function(a){a.preventDefault()});this.body.find("form").on("submit",function(a){a.preventDefault()});var a=!1;b(window).on("beforeunload.CE.Iframe",function(){a=!0});b(CE.Iframe.window).on("beforeunload.CE.Iframe",function(){if(!a)return localStorage.getItem("postSaveAlert");
a=!1})},resizeWindow:function(){CE.Iframe.window.CE.Utils.triggerWindowEvent("resize")},setMinWidth:function(){this.element.css("min-width",this.minWidth)},unsetMinWidth:function(){this.element.css("min-width","")}})});
steal("jquery/controller",function(b){b.Controller("CE.Navbar",{myThis:null},{iframe:b("#motopress-content-editor-scene"),editorEl:b("#motopress-content-editor"),editorWrapperEl:b("#motopress-content-editor-scene-wrapper"),scrollWidth:15,postStatus:null,postType:null,wpPostForm:null,presetsMetaField:null,privatesMetaField:null,postNameObj:null,postNameObjInput:null,wpPostNameForm:null,wpPostNameFormPrompt:null,wpPostName:null,tutorialsCounter:0,$titles:null,hiddenChar:"&zwnj;",hiddenCharUnicode:"\u200c",
init:function(a){CE.Navbar.myThis=this;CE.Iframe.myThis=null;this.wpPostForm=b('form[name="post"]');this.wpPostNameForm=this.wpPostForm.find('input[name="post_title"]');this.wpPostNameFormPrompt=this.wpPostForm.find("#title-prompt-text");this.presetsMetaField=this.wpPostForm.find('textarea[name="'+motopressCE.styleEditor["const"].wpPostMetaPresetStyles+'"]');this.privatesMetaField=this.wpPostForm.find('textarea[name="'+motopressCE.styleEditor["const"].wpPostMetaPrivateStyle+'"]');this.postType=a.find(".motopress-page-name #motopress-post-type").text();
this.postNameObj=a.find(".motopress-page-name #motopress-title");this.postNameObjInput=a.find(".motopress-page-name").children("#motopress-input-edit-title");this.addWidgetBtn=a.find("#mpce-add-widget");this.setupBtns();b('link[href*="js_composer"]').remove();this.showContentEditor();b("#motopress-ce-btn").on("click",function(){CE.Navbar.myThis.iframe=b("#motopress-content-editor-scene");MP.Preloader.myThis.reopen();new MP.Preloader(b("#motopress-preload"));new CE.Iframe(CE.Navbar.myThis.iframe);
CE.Navbar.myThis.showContentEditor()});0===this.editorWrapperEl.height()&&(a=this.editorWrapperEl.parent().height()-53,0<a&&this.editorWrapperEl.height(a),a=this.editorEl.parent().height()-32,0<a&&this.editorEl.height(a),b(window).resize(function(){var a=CE.Navbar.myThis.editorWrapperEl.parent().height()-53;0<a&&CE.Navbar.myThis.editorWrapperEl.height(a);a=CE.Navbar.myThis.editorEl.parent().height()-32;0<a&&CE.Navbar.myThis.editorEl.height(a)}));MP.Preloader.myThis.load(CE.Navbar.shortName)},_destroy:function(){this.setWidgetBtnInactive()},
onIframeLoad:function(a){this.wpPostName=this.wpPostNameForm.val();0===this.wpPostName.length?(this.postNameObj.empty().append(b("<i />",{text:localStorage.getItem("CEEmptyPostTitle")})),this.postNameObjInput.val("")):(this.postNameObj.text(this.wpPostName),this.postNameObjInput.val(this.wpPostName));var c=new RegExp("["+this.hiddenCharUnicode+"]+");this.$titles=CE.Iframe.contents.find(":header:not(:has(canvas))").filter(function(){return c.test(b(this).text())});this.scrollWidth=MP.Utils.getScrollbarWidth();
a=this.scrollWidth+724+80;CE.Iframe.myThis.minWidth=a;CE.Iframe.myThis.setMinWidth();b(".motopress-content-editor-navbar.ce_navbar").css("min-width",a)},setupBtns:function(){var a="";b("form#post input#save-post").length?(this.postStatus="draft",a=localStorage.getItem("CEPublishBtnText")):(this.postStatus="published",a=localStorage.getItem("CEUpdateBtnText"),b("#motopress-content-editor-save").hide());b("#motopress-content-editor-publish").text(a)},"#motopress-title click":function(a,b){this.postNameObj.addClass("motopress-hide");
this.postNameObjInput.removeClass("motopress-hide").select()},"#motopress-input-edit-title blur":function(a,c){var d=a[0];""==d.value?(this.postNameObj.empty().append(b("<i />",{text:localStorage.getItem("CEEmptyPostTitle")})),this.wpPostNameForm.val(d.value),this.wpPostNameFormPrompt.removeClass("screen-reader-text")):(this.postNameObj.text(d.value),this.wpPostNameForm.val(d.value),this.wpPostNameFormPrompt.addClass("screen-reader-text"));this.renderTitle(d.value);this.postNameObjInput.addClass("motopress-hide");
this.postNameObj.removeClass("motopress-hide");CE.Save.changeContent()},"#motopress-input-edit-title keypress":function(a,c){var d=a[0];"13"==c.keyCode&&(""==d.value?(this.postNameObj.empty().append(b("<i />",{text:localStorage.getItem("CEEmptyPostTitle")})),this.wpPostNameForm.val(d.value),this.wpPostNameFormPrompt.removeClass("screen-reader-text")):(this.postNameObj.text(d.value),this.wpPostNameForm.val(d.value),this.wpPostNameFormPrompt.addClass("screen-reader-text")),this.renderTitle(d.value),
this.postNameObjInput.addClass("motopress-hide"),this.postNameObj.removeClass("motopress-hide"),CE.Save.changeContent())},"#motopress-content-editor-tutorials click":function(a){var b=jQuery("#motopress-tutorials-modal");jQuery("body");b.mpmodal("toggle");0===this.tutorialsCounter&&jQuery.ajax({type:"post",dataType:"html",url:motopress.ajaxUrl,data:{action:"motopress_tutorials"},success:function(a){0!=a&&"nothing"!=a?b.find(".modal-body").html(a):b.find(".modal-body").html("<h1>Error: can't load tutorials.<h1>")}});
this.tutorialsCounter++},"#motopress-content-editor-publish click":function(a){CE.Save.convertAndInsert();if(a.hasClass("motopress-ajax-update")){a.prop("disabled",!0).text(localStorage.getItem("CEUpdating"));var b=this;CE.Save.saveAJAX().done(function(){a.prop("disabled",!1).text(localStorage.getItem("CEUpdateBtnText"));var d=jQuery("#post-preview").attr("href");MP.Flash.setFlash(parent.MP.Utils.strtr(localStorage.getItem("CEPostSaved"),{"%postType%":b.postType,"%link%":d,"%preview%":localStorage.getItem("CEPreviewBtnText")}),
"success");MP.Flash.showMessage()})}else MP.Preloader.myThis.show(),this.setPluginAutoOpen(!0),CE.Save.publishWithReload()},"#motopress-content-editor-save click":function(a){CE.Save.convertAndInsert();var b=this;a.hasClass("motopress-ajax-update")?(a.prop("disabled",!0).text(localStorage.getItem("CESaving")),CE.Save.saveAJAX().done(function(){a.prop("disabled",!1).text(localStorage.getItem("CESaveBtnText"));var d=jQuery("#post-preview").attr("href");MP.Flash.setFlash(parent.MP.Utils.strtr(localStorage.getItem("CEPostSaved"),
{"%postType%":b.postType,"%link%":d,"%preview%":localStorage.getItem("CEPreviewBtnText")}),"success");MP.Flash.showMessage()})):(MP.Preloader.myThis.show(),CE.Navbar.myThis.setPluginAutoOpen(!0),CE.Save.saveWithReload())},"#motopress-content-editor-preview click":function(){CE.Save.convertAndInsert();b("form#post #post-preview").click()},"#mpce-add-widget click":function(a){a.hasClass("active")?(this.setWidgetBtnInactive(),this.setLeftBarInactive()):(this.setWidgetBtnActive(),this.setLeftBarActive())},
setWidgetBtnActive:function(){this.addWidgetBtn.addClass("active")},setWidgetBtnInactive:function(){this.addWidgetBtn.removeClass("active")},setLeftBarActive:function(){CE.Iframe.window.CE.LeftBar.myThis.setActive();CE.Iframe.window.CE.LeftBar.myThis.show(!0)},setLeftBarInactive:function(){CE.Iframe.window.CE.LeftBar.myThis.setInactive();CE.Iframe.window.CE.LeftBar.myThis.hide(!0)},"#motopress-content-editor-delete click":function(){CE.Iframe.window.CE.Tools.myThis.removeBlock();CE.Save.changeContent()},
"#motopress-content-editor-close click":function(){CE.Save.convertAndInsert();this.hideContentEditor();MP.Utils.removeWindowFix();MP.Utils.removeWpFrontEndEditorFix();this.hideObjectControlBtns();this.iframe.remove();MP.Editor.myThis.close()},"#motopress-content-editor-device-mode-preview click":function(a,b){this.hide();CE.PreviewDevice.myThis.show();CE.PreviewDevice.myThis.preview("desktop")},hide:function(){this.abortShow();this.element.addClass("motopress-ce-navbar-hide").one("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd",
function(a,b){CE.Navbar.myThis.element.addClass("motopress-hide");CE.Navbar.myThis.element.removeClass("motopress-ce-navbar-hide")})},show:function(){this.abortHide();this.element.addClass("motopress-ce-navbar-show").removeClass("motopress-hide").one("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd",function(){CE.Navbar.myThis.element.removeClass("motopress-ce-navbar-show")})},abortShow:function(){this.element.removeClass("motopress-ce-navbar-show").off("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd")},
abortHide:function(){this.element.removeClass("motopress-ce-navbar-hide").off("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd")},renderTitle:function(a){var c=this;this.$titles.each(function(){b(this).html(b(this).html().replace(new RegExp(c.hiddenCharUnicode+".*"+c.hiddenCharUnicode,"g"),c.hiddenChar+a+c.hiddenChar))})},hideContentEditor:function(){MP.Error.terminate()},showContentEditor:function(){b("html").css({overflow:"hidden",paddingTop:0});this.editorEl.siblings(':not("#'+MP.Preloader.myThis.element.attr("id")+
', script, link")').each(function(){b(this).is(":hidden")||b(this).addClass("motopress-hide")});b("#wpwrap").height("100%").children("#wpcontent").children("#wpadminbar").prependTo("body");this.editorEl.show()},showObjectControlBtns:function(){b(".motopress-object-control-btns").css("display","inline-block")},hideObjectControlBtns:function(){b(".motopress-object-control-btns").hide()},setPluginAutoOpen:function(a){sessionStorage.setItem("motopressPluginAutoOpen",a)},getPluginAutoOpen:function(){sessionStorage.getItem("motopressPluginAutoOpen")}})});
steal("jquery/class",function(b){b.Class("CE.Save",{isContentChanged:!1,excerpt:"",contentSavedInCE:!1,isNeedSaveExcerpt:!1,compareString:"",storedBeforeunload:[],_storeEditorIsDirtyFunc:null,_editorIsDirty:!1,_hasDirtyFunc:!1,wpEditor:null,init:function(){this.wpEditor=tinyMCE.get("content");this.storeEditorFunc();this.storeWpEvents();MP.Editor.on("EditorOpen",this.proxy("open"));MP.Editor.on("EditorClose",this.proxy("close"))},open:function(){this.bindCustomEditorFunc()},close:function(){this.unbindCustomEditorFunc();
this.bindWpEvents()},getCompareString:function(){return(b("#title").val()||"")+"::"+(b("#content").val()||"")+"::"+(b("#excerpt").val()||"")},saveWithReload:function(){this.saveContent();b("form#post #save-post").click()},publishWithReload:function(){this.saveContent();b("form#post #publish").click()},saveAJAX:function(){this.saveContent();var a=b("form#post").serializeArray(),c=this;return b.ajax({type:"post",data:a,success:function(a){MP.Editor.triggerEverywhere("AfterUpdate");c.contentSavedInCE=
!0},error:function(a){console.log(a)}})},saveContent:function(){MP.Editor.triggerEverywhere("BeforeSave");this.isContentChanged=!1;CE.Save._editorIsDirty=!1;this.unbindWpEvents()},convertAndInsert:function(){var a=CE.Iframe.contents.find("body .motopress-content-wrapper");a.length&&(this.isNeedSaveExcerpt=!1,a=this.getSources("",a),null!==parent.CE.Iframe.wpEditor?(this.excerpt="",parent.CE.Iframe.wpEditor.setContent(a,{format:"html"}),tinyMCE.triggerSave()):parent.CE.Iframe.wpTextarea.val(parent.switchEditors._wp_Nop(a)),
parent.MP.Settings.saveExcerpt&&this.isNeedSaveExcerpt&&(a=b("#postexcerpt #excerpt",parent.document),a.length&&a.val(parent.switchEditors._wp_Nop(this.excerpt))))},getSources:function(a,c,d){"undefined"===typeof d&&(d=1);var e=this,f=null,g=null,f=1===d?parent.CE.Iframe.myThis.gridObj.row.shortcode:parent.CE.Iframe.myThis.gridObj.row.inner;c.children(".motopress-row, .mpce-wp-more-tag").each(function(){var c=b(this);if(1===d&&c.hasClass("mpce-wp-more-tag"))e.isNeedSaveExcerpt=!0,e.excerpt=a,a+="\x3c!--more--\x3e";
else{var k=parent.MP.Utils.getEdgeRow(b(this));a+="<p>["+f+e.getAttributes(c)+"]</p>";k.children(".motopress-clmn").each(function(){var c=b(this),f=MP.Utils.getEdgeSpan(c),k=MP.Utils.getSpanClass(c.prop("class").split(" ")),k=MP.Utils.getSpanNumber(k),h="",l="",l=c.get(0).style.minHeight;if(l.length){var n=parseInt(l);isNaN(n)||n===CE.Iframe.window.CE.Resizer.myThis.minHeight||n===CE.Iframe.window.CE.Resizer.myThis.spaceMinHeight||(h=' style="min-height: '+l+';"')}parent.CE.Iframe.myThis.gridObj.span.type&&
"multiple"===parent.CE.Iframe.myThis.gridObj.span.type?(g=1===d?parent.CE.Iframe.myThis.gridObj.span.shortcode[k-1]:parent.CE.Iframe.myThis.gridObj.span.inner[k-1],l=""):(l=" "+parent.CE.Iframe.myThis.gridObj.span.attr+'="'+k+'"',g=1===d?parent.CE.Iframe.myThis.gridObj.span.shortcode:parent.CE.Iframe.myThis.gridObj.span.inner);a+="<p>["+g+l+h+e.getAttributes(c)+"]</p>";a=f.children(".motopress-row").length?e.getSources(a,f,d+1):e.getShortcode(a,f.find(".motopress-block-content > [data-motopress-shortcode]"));
a+="<p>[/"+g+"]</p>"});a+="<p>[/"+f+"]</p>"}});return a},getShortcode:function(a,b){if(b.length){var d="",e=b.attr("data-motopress-shortcode"),f=b.attr("data-motopress-close-type"),g="undefined"===typeof b.attr("data-motopress-unwrap")?!1:!0,h="",k="";"enclosed"===f&&(f=(f=b.attr("data-motopress-content"))?f.replace(/\[\]/g,"["):"",d+=f,k="<p>[/"+e+"]</p>");g&&this.isEmptyStyles(b)||(h="<p>["+e+this.getAttributes(b)+"]</p>",d=h+d+k);a+=d}return a},changeContent:function(){!this.isContentChanged&&
parent.CE.Iframe.wpEditor&&(this.bindWpEvents(),this.isContentChanged=CE.Save._editorIsDirty=!0)},getAttributes:function(a){var c={},d=a.attr("data-motopress-parameters")?JSON.parse(a.attr("data-motopress-parameters")):{},e=a.attr("data-motopress-styles")?JSON.parse(a.attr("data-motopress-styles")):{};b.extend(c,d,e);var f="";if(c){var d=a.attr("data-motopress-group"),g=a.attr("data-motopress-shortcode"),h=CE.Iframe.window.CE.LeftBar.myThis.library[d].objects[g].parameters;if(g===parent.CE.Iframe.myThis.gridObj.span.shortcode||
g===parent.CE.Iframe.myThis.gridObj.span.inner)a.hasClass("motopress-empty")&&(c.hasOwnProperty(parent.CE.Iframe.myThis.gridObj.span.custom_class_attr)||(c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr]={}),c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr].hasOwnProperty("value")||(c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr].value=""),c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr].value+=" motopress-empty mp-hidden-phone"),a.hasClass("motopress-space")&&(c.hasOwnProperty(parent.CE.Iframe.myThis.gridObj.span.custom_class_attr)||
(c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr]={}),c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr].hasOwnProperty("value")||(c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr].value=""),c[parent.CE.Iframe.myThis.gridObj.span.custom_class_attr].value+=" motopress-space");b.each(c,function(a,d){h.hasOwnProperty(a)&&h[a].hasOwnProperty("saveInContent")&&"true"==h[a].saveInContent&&(d.value="");if(-1!==b.inArray(g,["mp_row","mp_row_inner"])){if(h.hasOwnProperty(a)&&"undefined"!==
typeof h[a].disabled&&"true"===h[a].disabled&&-1!==b.inArray(a,"bg_video_youtube bg_video_youtube_cover bg_video_webm bg_video_mp4 bg_video_ogg bg_video_cover parallax_image".split(" ")))return;"full_height"===a&&h.hasOwnProperty(a)&&h[a]["default"]===d.value&&(d.value="");if(h.hasOwnProperty(a)&&h[a].dependency&&c[h[a].dependency.parameter].value!==h[a].dependency.value&&("undefined"===typeof h[a].disabled||"false"===h[a].disabled))return}"undefined"!==typeof d.value&&""!==d.value&&(f+=" "+a+'="'+
d.value+'"')})}return f},storeWpEvents:function(){var a=[],a=MP.Utils.version_compare(b.fn.jquery,"1.8","<")?b(window).data("events").beforeunload:b._data(window,"events").beforeunload;"undefined"!==typeof a&&(this.storedBeforeunload=a.slice());"function"===typeof window.onbeforeunload&&(this.storedBeforeunload.unshift({handler:window.onbeforeunload,namespace:"edit-post"}),window.onbeforeunload=null)},storeEditorFunc:function(){this.wpEditor&&"undefined"!==typeof this.wpEditor.isDirty?(this._storeEditorIsDirtyFunc=
this.wpEditor.isDirty,this._hasDirtyFunc=!0):this._hasDirtyFunc=!1},bindCustomEditorFunc:function(){this._hasDirtyFunc&&(this.wpEditor.focus(),this.wpEditor.isDirty=this._editorIsDirtyFunc,tinyMCE.activeEditor.isDirty=this._editorIsDirtyFunc)},unbindCustomEditorFunc:function(){this._hasDirtyFunc&&(this.wpEditor.isDirty=this._storeEditorIsDirtyFunc,tinyMCE.activeEditor.isDirty=this._storeEditorIsDirtyFunc)},_editorIsDirtyFunc:function(){return CE.Save._editorIsDirty},bindWpEvents:function(){if("undefined"!==
typeof this.storedBeforeunload&&this.storedBeforeunload.length){this.unbindWpEvents();for(var a=0;a<this.storedBeforeunload.length;a++)"edit-post"===this.storedBeforeunload[a].namespace&&b(window).bind("beforeunload.edit-post",this.storedBeforeunload[a].handler)}},unbindWpEvents:function(){b(window).unbind("beforeunload.edit-post")},isEmptyStyles:function(a){var c=!0;a=a.attr("data-motopress-styles")?JSON.parse(a.attr("data-motopress-styles")):{};b.each(a,function(a,b){"undefined"!==typeof b.value&&
""!==b.value&&(c=!1)});return c}},{})});
steal("jquery/class",function(b){b.Class("MP.Settings",{siteUrl:null,debug:null,adminUrl:null,pluginRootUrl:null,pluginName:null,pluginDirUrl:null,palettes:null,lang:null,langName:null,loadScriptsUrl:null,spellcheck:null,saveExcerpt:null,removeWpPanels:function(){b("#footer, #adminmenuwrap, #adminmenuback, .update-nag").remove();b("#wpcontent").css("margin-left",0);b("#wpbody-content").css("padding-bottom",0);b("#wpfooter").remove()},getSiteUrl:function(){var a=window.location.href,b=a.indexOf("/wp-admin/");
this.siteUrl=a.substr(0,b)},getWpSettings:function(){var a=motopressCE.settings.wp;MP.Settings.debug=a.debug;MP.Settings.adminUrl=a.admin_url;MP.Settings.pluginRootUrl=a.plugin_root_url;MP.Settings.pluginName=a.plugin_name;MP.Settings.pluginDirUrl=a.plugin_dir_url;MP.Settings.palettes=a.palettes;MP.Settings.licenseType=a.license_type;MP.Settings.lang=a.lang;MP.Settings.loadScriptsUrl=a.load_scripts_url;MP.Settings.spellcheck="1"==a.spellcheck;MP.Settings.saveExcerpt="1"===a.save_excerpt;if(MP.Utils.Browser.IE||
MP.Utils.Browser.Opera)window.location=MP.Settings.adminUrl+"?page="+MP.Settings.pluginName}},{setup:function(){"undefined"===typeof CE&&this.removeWpPanels();MP.Settings.getSiteUrl();MP.Settings.getWpSettings()}})});steal("jquery/class",function(b){b.Class("MP.Language",{init:function(){}},{init:function(){localStorage.clear();b.each(motopressCE.settings.translations,function(a,b){localStorage.setItem(a,b)});MP.Preloader.myThis.load(MP.Language.shortName)}})});
steal("jquery/controller",function(b){b.Controller("CE.CodeModal",{myThis:null,currentShortcode:null,currentTextareaTinymce:null,listensTo:["show","shown","hide"]},{iframeBody:null,content:null,editor:null,saveBtn:null,saveHandler:null,isHiding:!1,init:function(){CE.CodeModal.myThis=this;this.container=this.element.find("#wp-motopresscodecontent-editor-container");this.content=this.element.find("#motopresscodecontent");"undefined"!==typeof tinyMCE&&"undefined"!==typeof tinyMCE.get("motopresscodecontent")&&
(this.editor=tinyMCE.get("motopresscodecontent"));this.saveBtn=this.element.find("#motopress-save-code-content");var a=this.element.find("#wp-motopresscodecontent-editor-tools");0===a.height()&&a.height(33);this.element.mpmodal({backdrop:"static",show:!1});b(window).on("resize",this.proxy("resize"));MP.Utils.addWindowFix();if(parent.MP.Utils.version_compare(parent.motopressCE.settings.wp.wordpress_version,"4.0.0",">="))this.element.find(".wp-switch-editor.switch-html, .wp-switch-editor.switch-tmce").on("click",
function(){CE.CodeModal.myThis.recalcTabSizeWP4()})},setSize:function(a){var b=this.element.find(".modal-footer"),d=this.element.width()-(parseFloat(b.css("padding-left"))+parseFloat(b.css("padding-right")));b.width(d);d=this.element.find(".modal-body");b=this.element.height()-this.element.find(".modal-header").outerHeight()-parseFloat(d.css("margin-top"))-parseFloat(d.css("margin-bottom"))-b.outerHeight();d.height(b);a&&this.element.css({display:"block",visibility:"hidden"});b=parent.MP.Utils.version_compare(parent.motopressCE.settings.wp.wordpress_version,
"4.1.0",">=")?2:0;b=this.element.find("#wp-motopresscodecontent-wrap").height()-this.element.find("#wp-motopresscodecontent-editor-tools").outerHeight()-parseFloat(this.container.css("border-top-width"))-parseFloat(this.container.css("border-bottom-width"))-b;this.container.height(b);parent.MP.Utils.version_compare(parent.motopressCE.settings.wp.wordpress_version,"4.0.0","<")?this.recalcTabSizeWPOld():this.recalcTabSizeWP4();a&&(this.element.css({display:"",visibility:""}),this.content.removeAttr("rows"))},
recalcTabSizeWPOld:function(){var a=this.container.height()-parseFloat(this.container.css("border-top-width"))-parseFloat(this.container.css("border-bottom-width"))-this.element.find("#qt_motopresscodecontent_toolbar").outerHeight()-parseFloat(this.content.css("padding-top"))-parseFloat(this.content.css("padding-bottom"));this.content.height(a);var a=this.element.find("#motopresscodecontent_ifr"),b=this.container.find(".mce-first, tr.mceFirst").first(),d=this.container.find(".mce-statusbar, tr.mceLast").last(),
b=this.container.height()-parseFloat(this.container.css("border-top-width"))-parseFloat(this.container.css("border-bottom-width"))-b.outerHeight()-d.outerHeight();a.height(b)},recalcTabSizeWP4:function(){switch(MP.Utils.getEditorActiveMode(this.element.find("#wp-motopresscodecontent-wrap").prop("class").split(" "))){case "html-active":var a=this.container.height()-this.element.find("#qt_motopresscodecontent_toolbar").outerHeight()-parseFloat(this.content.css("padding-top"))-parseFloat(this.content.css("padding-bottom"));
this.content.height(a);break;case "tmce-active":a=this.container.height()-parseFloat(this.container.find(".mce-toolbar-grp").outerHeight())-parseFloat(this.container.find(".mce-statusbar").outerHeight()),this.container.find(".mce-edit-area").height(a)}},resize:function(){this.element.data("modal").isShown&&this.setSize(!1)},show:function(a,b){this.isHiding=!1;this.switchVisual();this.setSize(!0);if(null!==this.saveHandler&&"function"===typeof this.saveHandler)this.saveBtn.off("click").on("click",
this.saveHandler);null===this.iframeBody&&(this.iframeBody=this.element.find("#motopresscodecontent_ifr").contents().find(".motopresscodecontent"),this.iframeBody.css("max-width","none"));CE.Iframe.window.CE.Dialog.myThis.element.dialog("isOpen")&&!a.data("modal").hasOwnProperty("closeDialog")&&CE.Iframe.window.CE.Dialog.myThis.element.dialog("close")},shown:function(){null!==this.editor?this.editor.execCommand("mceFocus",!1):this.content.focus();b("body").hide(0,function(){b("body").show()})},hide:function(a,
b){if(!this.isHiding){this.isHiding=!0;var d=CE.CodeModal.currentShortcode.closest(".motopress-clmn").find("."+CE.Iframe.window.CE.DragDrop.myThis.helper.attr("class")).first().children("."+CE.Iframe.window.CE.DragDrop.myThis.dragHandle.attr("class"));d.prev().focus();this.content.val("");null!==this.editor&&this.editor.setContent("");this.saveHandler=null;null!==CE.Iframe.wpEditor&&CE.Iframe.wpEditor.focus();a.data("modal").hasOwnProperty("closeDialog")&&delete a.data("modal").closeDialog;CE.Iframe.window.CE.Dialog.myThis.element.dialog("isOpen")||
CE.Iframe.window.CE.Dialog.myThis.open(d);var e=setTimeout(function(){CE.CodeModal.currentShortcode=null;CE.CodeModal.currentTextareaTinymce=null;clearTimeout(e)},0)}},switchVisual:function(){var a=MP.Utils.getEditorActiveMode(this.element.find("#wp-motopresscodecontent-wrap").prop("class").split(" "));"undefined"!==typeof tinyMCE&&"html-active"===a&&(switchEditors.hasOwnProperty("switchto")?switchEditors.switchto(this.element.find("#motopresscodecontent-tmce")[0]):switchEditors.go("motopresscodecontent",
"tmce"),null===this.editor&&(this.editor=tinyMCE.get("motopresscodecontent")))}})});
steal("jquery/controller",function(b){b.Controller("CE.PreviewDevice",{myThis:null},{mode:null,previewClassPrefix:"motopress-ce-device-mode-",init:function(a){CE.PreviewDevice.myThis=this},hide:function(){this.abortShow();this.element.addClass("motopress-content-editor-preview-device-panel-hide").one("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd",function(a,b){CE.PreviewDevice.myThis.element.addClass("motopress-hide").removeClass("motopress-content-editor-preview-device-panel-hide")})},isHiding:function(){return this.element.hasClass("motopress-content-editor-preview-device-panel-hide")},
show:function(){this.abortHide();this.element.addClass("motopress-content-editor-preview-device-panel-show").removeClass("motopress-hide").one("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd",function(a,b){CE.PreviewDevice.myThis.element.removeClass("motopress-content-editor-preview-device-panel-show")})},abortShow:function(){this.element.removeClass("motopress-content-editor-preview-device-panel-show").off("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd")},abortHide:function(){this.element.removeClass("motopress-content-editor-preview-device-panel-hide").off("animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd")},
".motopress-content-editor-preview-mode-btn click":function(a,c){this.isHiding()&&(this.show(),CE.Navbar.myThis.hide());var d=b(a).attr("data-mode");this.preview(d)},".motopress-content-editor-preview-edit click":function(a,b){this.unsetPreview();this.hide();CE.Navbar.myThis.show()},preview:function(a){null===this.mode&&(CE.Iframe.window.CE.Selectable.myThis.unselect(),CE.Iframe.window.CE.StyleEditor.myThis.unsetEmulateCSSMode(),CE.Iframe.window.CE.InlineEditor.destroyAll(),CE.Iframe.window.CE.Utils.addSceneAction("device-preview"),
CE.Iframe.myThis.unsetMinWidth());if(a!==this.mode){var b=null!==this.mode?this.previewClassPrefix+this.mode:"",d=this.previewClassPrefix+a;CE.Navbar.myThis.iframe.removeClass(b).addClass(d);CE.Navbar.myThis.editorWrapperEl.addClass("motopress-ce-full-height");CE.Iframe.myThis.body.removeClass(b).addClass(d);CE.Iframe.window.CE.Utils.triggerWindowEvent("resize");this.mode=a}},unsetPreview:function(){var a=this.previewClassPrefix+this.mode;CE.Navbar.myThis.iframe.removeClass(a);CE.Iframe.window.CE.StyleEditor.myThis.setEmulateCSSMode();
CE.Iframe.window.CE.InlineEditor.reinitAll();CE.Navbar.myThis.editorWrapperEl.removeClass("motopress-ce-full-height");CE.Iframe.myThis.body.removeClass(a);CE.Iframe.myThis.setMinWidth();CE.Iframe.window.CE.Utils.removeSceneAction("device-preview");this.mode=null}})});
