# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('biography', models.TextField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('adress', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state_providence', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, choices=[(b'SPAIN', b'Spain'), (b'GERMANY', b'Germany'), (b'FRANCE', b'France'), (b'USA', b'United States Of America'), (b'CANADA', b'Canada'), (b'RUSSIA', b'Russia'), (b'CHINA', b'China'), (b'OTHER', b'Other')], default=b'OTHER', max_length=50)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name', 'country'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(verbose_name=b'date published')),
                ('resource_file', models.FileField(blank=True, upload_to=None)),
                ('url', models.URLField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('abstract', models.TextField(blank=True, max_length=300)),
                ('journal', models.CharField(blank=True, max_length=30)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('startpage', models.IntegerField(blank=True, null=True)),
                ('endpage', models.IntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=30)),
                ('edition', models.CharField(blank=True, max_length=30)),
                ('sourcetype', models.CharField(blank=True, choices=[(b'TEXTBOOK', b'Textbook'), (b'NOVEL', b'Novel'), (b'BIOGRAPHY', b'Biography'), (b'LETTER', b'Letter'), (b'INTERVIEW', b'Interview'), (b'ACADEMIC_PAPER', b'Academic Paper'), (b'NEWSPAPER_ARTICLE', b'Newspaper Article'), (b'JOURNAL', b'Journal'), (b'BOOK', b'Book'), (b'CONFERENCE_PAPER', b'Conference Paper'), (b'BLOG', b'Blog'), (b'OTHER', b'Other')], default=b'OTHER', max_length=30)),
                ('authors', models.ManyToManyField(to='api.Author')),
                ('categories', models.ManyToManyField(blank=True, to='api.Category')),
                ('editors', models.ManyToManyField(blank=True, to='api.Editor')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Publisher')),
            ],
            options={
                'ordering': ['-date', 'title'],
                'get_latest_by': 'date',
            },
        ),
    ]
