# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160516_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
