# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160516_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='accessed',
            field=models.DateField(blank=True, null=True, verbose_name='date accessed'),
        ),
    ]
