# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resource_accessed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'get_latest_by': 'published', 'ordering': ['-published', 'title']},
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='date',
            new_name='published',
        ),
    ]
