# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160608_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='edition',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='journal',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='series',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
