# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160608_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='fulltext',
            field=models.TextField(blank=True),
        ),
    ]
