# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 20:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resource_fulltext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='authors',
        ),
        migrations.AddField(
            model_name='resource',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='resource',
            name='editors',
        ),
        migrations.AddField(
            model_name='resource',
            name='editors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='keywords',
        ),
        migrations.AddField(
            model_name='resource',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
