# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resource_fulltext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_file',
        ),
        migrations.AddField(
            model_name='resource',
            name='fulltext_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
