# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160619_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='fulltext_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='fulltext URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sourcetype',
            field=models.CharField(blank=True, choices=[('NEWSPAPER', 'Newspaper'), ('JOURNAL', 'Journal'), ('BOOK', 'Book'), ('CONFERENCE', 'Conference'), ('BLOG', 'Blog'), ('OTHER', 'Other')], help_text='The type of the source, e.g., “book” for a book chapter.', max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='URL'),
        ),
    ]
